# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5171680750b44f0348d9faf51aa0af86ad931c45557473f7919580df689e4d0fd1ab9da33dca219c58f2e553915f3614a5cfbc5cc12bd0e1dcd4dda609da931b

test:
  secret_key_base: 3faa0e4509516df683a191ead51f8b43d5f61e0db2615376e1a6c6af442d2342d94e0bede75fdb96254bad7ec487c15ce5845207eb21b8cae212ef8e6eaf88c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
